CREATE TABLE APPROVAL.CC_EMP
(
    EMP_ID             INT       NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    EMP_EMAIL          VARCHAR   NOT NULL UNIQUE KEY,
    EMP_PHONENUM       VARCHAR   NOT NULL UNIQUE KEY,
    EMP_PW             VARCHAR   NOT NULL,
    EMP_NAME           VARCHAR   NULL,
    EMP_BIRTH          TIMESTAMP NOT NULL,
    EMP_ACCOUNT_STATUS CHAR      NOT NULL DEFAULT 'Y',
    EMP_POSITION       VARCHAR   NULL     DEFAULT NULL,
    PW_ERROR_CNT       INT       NOT NULL DEFAULT 0,
    EMP_JOIN_DT        TIMESTAMP NULL     DEFAULT NULL,
    EMP_RETIRE_DT      TIMESTAMP NULL     DEFAULT NULL,
    ROLE_ID            INT       NOT NULL,
    DEPARTMENT_ID      INT       NULL     DEFAULT NULL, #FK:CC_DEP
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES CC_DEP (DEPARTMENT_ID),
    RANK_ID            INT       NULL     DEFAULT NULL, #FK:CC_RANK
    FOREIGN KEY (RANK_ID) REFERENCES CC_RANK (RANK_ID),
    COMPANY_NO         VARCHAR   NULL     DEFAULT NULL, #FK:COMPANY
    FOREIGN KEY (COMPANY_NO) REFERENCES COMPANY (COMPANY_NO),
    DIRECT_BOSS_ID     INT       NULL,                  #FK:CC_EMP
    FOREIGN KEY (DIRECT_BOSS_ID) REFERENCES CC_EMP (DIRECT_BOSS_ID),
    SPARE              VARCHAR(200)
);

CREATE TABLE APPROVAL.EMP_LEAVE
(
    LEAVE_SEQ      INT       NOT NULL PRIMARY KEY UNIQUE KEY,
    LEAVE_TYPE     INT       NOT NULL,
    LEAVE_USE_DT   INT       NOT NULL,
    LEAVE_START_DT TIMESTAMP NOT NULL,
    EMP_ID         INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    DOC_NO         VARCHAR   NOT NULL, #FK:CC_APPRO
    FOREIGN KEY (DOC_NO) REFERENCES CC_APPRO (DOC_NO),
    SPARE          VARCHAR(200)
);

CREATE TABLE APPROVAL.EMP_COMMUTE
(
    EMP_COMMUTE_SEQ INT       NOT NULL PRIMARY KEY UNIQUE KEY,
    ATTENDANCE_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
    LEAVE_WORK_TIME TIMESTAMP NOT NULL DEFAULT NOW(),
    EMP_ID          INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    SPARE           VARCHAR(200)
);

CREATE TABLE APPROVAL.CC_APPRO
(
    DOC_NO            VARCHAR   NOT NULL PRIMARY KEY UNIQUE KEY,
    DOC_TYPE          INT       NOT NULL,
    EMP_ID            INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    RETENTION_PERIOD  TIMESTAMP NULL     DEFAULT NULL,
    DOC_TITLE         VARCHAR   NOT NULL,
    DOC_CONTENT       VARCHAR   NOT NULL,
    CREATE_DT         TIMESTAMP NOT NULL,
    DEADLINE_DT       TIMESTAMP NULL     DEFAULT NULL,
    DRAFT_YN          CHAR      NOT NULL DEFAULT 'N',
    DELETE_YN         CHAR      NOT NULL DEFAULT 'N',
    TOTAL_LINE_COUNT  INT       NOT NULL DEFAULT NULL,
    STATUS_LINE_COUNT INT       NULL,
    SPARE             VARCHAR(200)
);

CREATE TABLE APPROVAL.APPRO_LINE
(
    STATUS_NO     INT       NOT NULL PRIMARY KEY UNIQUE KEY,
    LINE_TYPE     INT       NOT NULL,
    DOC_NO        INT       NOT NULL, #FK:CC_APPRO
    FOREIGN KEY (DOC_NO) REFERENCES CC_APPRO (DOC_NO),
    EMP_ID        INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    STATUS_CODE   INT       NULL DEFAULT NULL,
    APPRO_SEQ     INT       NULL,
    APPRO_DT      TIMESTAMP NULL DEFAULT NULL,
    APPRO_COMMENT VARCHAR   NULL DEFAULT NULL,
    COMMENT_DT    TIMESTAMP NULL DEFAULT NULL,
    SPARE         VARCHAR(200)
);

CREATE TABLE APPROVAL.APPRO_LINE_SYSTEM
(
    LINESET_NO INT       NOT NULL PRIMARY KEY UNIQUE KEY,
    LINE_TYPE  INT       NOT NULL,
    DOC_TYPE   INT       NOT NULL,
    CREATOR_NO INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (CREATOR_NO) REFERENCES CC_EMP (EMP_ID),
    APPRO_NO   INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (APPRO_NO) REFERENCES CC_EMP (EMP_ID),
    CREATE_DT  TIMESTAMP NOT NULL,
    UPDATE_DT  TIMESTAMP NULL     DEFAULT NULL,
    DELETE_YN  CHAR      NOT NULL DEFAULT 'N',
    APPRO_SEQ  INT       NULL,
    SPARE      VARCHAR(200)
);

CREATE TABLE APPROVAL.CC_TEM
(
    TEM_NO      INT       NOT NULL PRIMARY KEY UNIQUE KEY,
    DOC_TYPE    INT       NOT NULL,
    CREATOR_NO  INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (CREATOR_NO) REFERENCES CC_EMP (EMP_ID),
    DOC_TITLE   VARCHAR   NOT NULL,
    DOC_CONTENT VARCHAR   NOT NULL,
    CREATE_DT   TIMESTAMP NOT NULL,
    UPDATE_DT   TIMESTAMP NULL     DEFAULT NULL,
    DELETE_YN   CHAR      NOT NULL DEFAULT 'N',
    VIEW_LEVEL  INT       NOT NULL,
    SPARE       VARCHAR(200)
);

CREATE TABLE APPROVAL.CC_DEP
(
    DEPARTMENT_ID        INT     NOT NULL PRIMARY KEY UNIQUE KEY,
    PARENT_DEPARTMENT_ID INT     NULL, #FK:CC_DEP
    FOREIGN KEY (PARENT_DEPARTMENT_ID) REFERENCES CC_DEP (PARENT_DEPARTMENT_ID),
    DEPARTMENT_NAME      VARCHAR NOT NULL UNIQUE KEY,
    SPARE                VARCHAR(200)
);

CREATE TABLE APPROVAL.DEP_LEADER
(
    LEADER_ID     INT NOT NULL PRIMARY KEY UNIQUE KEY,
    DEPARTMENT_ID INT NOT NULL, #FK:CC_DEP
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES CC_DEP (DEPARTMENT_ID),
    EMP_ID        INT NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    SPARE         VARCHAR(200)
);

CREATE TABLE APPROVAL.CC_RANK
(
    RANK_ID        INT     NOT NULL PRIMARY KEY UNIQUE KEY,
    PARENT_RANK_ID INT     NULL, #FK:CC_RANK
    FOREIGN KEY (PARENT_RANK_ID) REFERENCES CC_RANK (PARENT_RANK_ID),
    RAND_NAME      VARCHAR NOT NULL,
    SPARE          VARCHAR(200)
);

CREATE TABLE APPROVAL.SCHEDULE_GROUP
(
    SCHEDULE_GROUP_ID          INT       NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    SCHEDULE_GROUP_NAME        VARCHAR   NOT NULL,
    SCHEDULE_GROUP_DESCRIPTION VARCHAR   NULL,
    SCHEDULE_GROUP_CREATE_DT   TIMESTAMP NOT NULL DEFAULT NOW(),
    SCHEDULE_GROUP_UPDATE_DT   TIMESTAMP NOT NULL DEFAULT NOW(),
    EMP_ID                     INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    SPARE                      VARCHAR(200)
);

CREATE TABLE APPROVAL.CC_SCHEDULE
(
    SCHEDULE_ID          INT       NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    SCHEDULE_NAME        INT       NOT NULL,
    SCHEDULE_CONTENT     VARCHAR   NULL     DEFAULT NULL,
    SCHEDULE_START_DT    TIMESTAMP NOT NULL,
    SCHEDULE_END_DT      TIMESTAMP NOT NULL,
    SCHEDULE_PLACE       VARCHAR   NULL     DEFAULT NULL,
    SCHEDULE_REGISTER_DT TIMESTAMP NOT NULL DEFAULT NOW(),
    SCHEDULE_UPDATE_DT   TIMESTAMP NOT NULL DEFAULT NOW(),
    ALLDAY_WHETHER       CHAR      NOT NULL DEFAULT 'N',
    SCHEDULE_GROUP_ID    INT       NOT NULL, #FK:SCHEDULE_GROUP
    FOREIGN KEY (SCHEDULE_GROUP_ID) REFERENCES SCHEDULE_GROUP (SCHEDULE_GROUP_ID),
    SPARE                VARCHAR(200)
);

CREATE TABLE APPROVAL.SCHEDULE_EMPLOYEES
(
    COL_SEQ     INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    SCHEDULE_ID INT NOT NULL, #FK:CC_SCHEDULE
    FOREIGN KEY (SCHEDULE_ID) REFERENCES CC_SCHEDULE (SCHEDULE_ID),
    EMP_ID      INT NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    SPARE       VARCHAR(200)
);

CREATE TABLE APPROVAL.SCHEDULE_GROUP_MEMBER
(
    SCHEDULE_GROUP_MEMBERS INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    SCHEDULE_GROUP_ID      INT NOT NULL, #FK:SCHEDULE_GROUP
    FOREIGN KEY (SCHEDULE_GROUP_ID) REFERENCES SCHEDULE_GROUP (SCHEDULE_GROUP_ID),
    EMP_ID                 INT NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    SPARE                  VARCHAR(200)
);

CREATE TABLE APPROVAL.CC_NOTICE
(
    NOTICE_NO       INT       NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    NOTICE_TITLE    VARCHAR   NOT NULL,
    NOTICE_CONTENT  VARCHAR   NOT NULL,
    COMMENT_YN      CHAR      NOT NULL DEFAULT 'Y',
    CREATE_DT       TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_DT       TIMESTAMP NULL     DEFAULT NULL,
    NOTIFICATION_YN CHAR      NOT NULL DEFAULT 'Y',
    DELETE_YN       CHAR      NOT NULL DEFAULT 'N',
    VIEW_COUNT      INT       NOT NULL DEFAULT 0,
    EMP_ID          INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    SPARE           VARCHAR(200)
);

CREATE TABLE APPROVAL.NOTICE_COMMENT
(
    COMMENT_NO INT       NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    NOTICE_NO  INT       NOT NULL, #FK:CC_NOTICE
    FOREIGN KEY (NOTICE_NO) REFERENCES CC_NOTICE (NOTICE_NO),
    CONTENT    VARCHAR   NOT NULL,
    CREATE_DT  TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_DT  TIMESTAMP NULL     DEFAULT NULL,
    DELETE_YN  CHAR      NOT NULL DEFAULT 'N',
    EMP_ID     INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    SPARE      VARCHAR(200)
);

CREATE TABLE APPROVAL.EMP_WORK_POLICY
(
    EMP_WORK_POLICY_ID INT       NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    DAY_OF_WEEK        VARCHAR   NOT NULL,
    WORK_WHETHER       CHAR      NOT NULL,
    WORK_START_TIME    TIMESTAMP NOT NULL DEFAULT NOW(),
    WORK_END_TIME      TIMESTAMP NOT NULL DEFAULT NOW(),
    EMP_ID             INT       NOT NULL, #FK:CC_EMP
    FOREIGN KEY (EMP_ID) REFERENCES CC_EMP (EMP_ID),
    SPARE              VARCHAR(200)
);

CREATE TABLE APPROVAL.COMPANY
(
    COMPANY_NO           INT       NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
    BIZ_NO               VARCHAR   NOT NULL UNIQUE KEY,
    COMPANY_NAME         VARCHAR   NOT NULL,
    COMPANY_ADDRESS      VARCHAR   NOT NULL,
    COMPANY_CALL         VARCHAR   NOT NULL,
    CREATE_DT            TIMESTAMP NOT NULL,
    UPDATE_DT            TIMESTAMP NULL,
    OCCUR_LEAVE_DT       TIMESTAMP NOT NULL,
    REMAIN_LEAVE_WHETHER CHAR      NOT NULL,
    DEFAULT_LEAVE_CNT    INT       NOT NULL,
    BASIC_WORK_HOURS     INT       NOT NULL,
    OVERTIME_PAY_WHETHER CHAR      NOT NULL,
    SPARE                VARCHAR(200)
);

CREATE TABLE APPROVAL.CC_CODE
(
    CODE_NO   INT     NOT NULL PRIMARY KEY UNIQUE KEY,
    CODE_TYPE VARCHAR NOT NULL,
    CODE_NAME VARCHAR NOT NULL,
    COL_SEQ   INT     NOT NULL,
    SPARE     VARCHAR(200)
);

CREATE TABLE APPROVAL.CC_FILES
(
    FILE_NO      INT       NOT NULL PRIMARY KEY UNIQUE KEY,
    ORIGIN_NAME  VARCHAR   NOT NULL,
    STORED_NAME  VARCHAR   NULL DEFAULT NULL,
    CREATE_DT    TIMESTAMP NOT NULL,
    UPDATE_DT    TIMESTAMP NULL DEFAULT NULL,
    FILE_SIZE    INT       NOT NULL,
    FILE_PATH    VARCHAR   NOT NULL,
    FILE_CONTENT VARCHAR   NOT NULL,
    SPARE        VARCHAR(200)
);

CREATE TABLE APPROVAL.FILES_TYPE
(
    TYPE_ID   INT  NOT NULL PRIMARY KEY UNIQUE KEY,
    FILE_NO   INT  NOT NULL, #FK:CC_FILES
    FOREIGN KEY (FILE_NO) REFERENCES CC_FILES (FILE_NO),
    TYPE_INFO CHAR NOT NULL,
    DOC_ID    INT  NOT NULL,
    SPARE     VARCHAR(200)
);

CREATE TABLE APPROVAL.LEAVE_POLICY
(
    LEAVE_POLICY_ID  INT NOT NULL PRIMARY KEY UNIQUE KEY,
    LEAVE_TYPE       INT NOT NULL,
    LEAVE_PROVIDE_DT INT NOT NULL,
    SPARE            VARCHAR(200)
);
